# Hyperparameter Search Configuration
# Defines search spaces and strategies for finding optimal sampler settings

# Search strategy options: grid, random, bayesian  
search_strategy: "bayesian"

# Number of iterations for random/bayesian search
n_iterations: 50

# Number of samples to generate per configuration for averaging
samples_per_config: 3

# Maximum length for generated text
max_length: 512

# Optional seed for reproducible results
seed: 42

# Sampler types to search over
sampler_types:
  - "top_p"
  - "min_p" 
  - "top_n_sigma"

# Parameter ranges for each sampler type
parameter_ranges:
  top_p:
    temperature: [0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3]
    top_p: [0.8, 0.85, 0.9, 0.92, 0.95, 0.97, 0.99]
    max_tokens: [512]
    
  min_p:
    temperature: [0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6]
    min_p: [0.005, 0.01, 0.015, 0.02, 0.03, 0.05, 0.08, 0.1, 0.15]
    max_tokens: [512]
    
  top_n_sigma:
    temperature: [0.8, 1.0, 1.2, 1.4, 1.5, 1.6, 1.8, 2.0, 2.2]
    top_n_sigma: [0.5, 0.8, 1.0, 1.2, 1.5, 1.8, 2.0, 2.5, 3.0]
    max_tokens: [512]

# Test prompts for creative writing evaluation
test_prompts:
  - "Write a short story about discovering a hidden room in an old library that contains books from parallel universes."
  - "Create a story where the protagonist can hear other people's thoughts, but only the thoughts they don't want to share."
  - "Tell a tale about a world where colors have started disappearing one by one, and your character is the only one who notices."
  - "Write about someone who wakes up with a completely different personality every morning."
  - "Create a story about a small café that exists in multiple dimensions simultaneously."

# Alternative configuration for intensive search
intensive_search:
  search_strategy: "grid"
  sampler_types: ["min_p", "top_n_sigma"]
  parameter_ranges:
    min_p:
      temperature: [0.9, 1.0, 1.1, 1.2, 1.3]
      min_p: [0.01, 0.02, 0.03, 0.05]
      max_tokens: [512]
    top_n_sigma:
      temperature: [1.0, 1.2, 1.5, 1.8, 2.0]
      top_n_sigma: [1.0, 1.5, 2.0, 2.5]
      max_tokens: [512]

# Quick test configuration  
quick_test:
  search_strategy: "random"
  n_iterations: 10
  samples_per_config: 2
  sampler_types: ["top_p", "min_p"]
  parameter_ranges:
    top_p:
      temperature: [0.8, 1.0, 1.2]
      top_p: [0.9, 0.95, 0.99]
      max_tokens: [512]
    min_p:
      temperature: [0.9, 1.1, 1.3]
      min_p: [0.02, 0.05, 0.1]
      max_tokens: [512]
  test_prompts:
    - "Write a brief story about time travel."
    - "Create a dialogue between two AI systems." 