# Creative Writing Sampling Presets
# Optimized configurations for story generation, dialogue, and creative content

# Core sampling presets for creative writing
presets:
  # Focused, coherent writing
  focused:
    description: "Focused, coherent writing with minimal repetition"
    sampler: "top_p"
    parameters:
      temperature: 0.7
      top_p: 0.9
      repeat_penalty: 1.1
      max_tokens: 512
      
  # Balanced creativity and coherence  
  balanced:
    description: "Balanced creativity and coherence for most creative tasks"
    sampler: "top_p"
    parameters:
      temperature: 0.8
      top_p: 0.95
      repeat_penalty: 1.1
      max_tokens: 512
      
  # High creativity for brainstorming
  creative:
    description: "High creativity and diversity for brainstorming and exploration"
    sampler: "top_p"
    parameters:
      temperature: 1.0
      top_p: 0.99
      repeat_penalty: 1.05
      max_tokens: 512
      
  # Experimental min-p for natural flow
  natural:
    description: "Natural flow using min-p sampling for organic text generation"
    sampler: "min_p"
    parameters:
      temperature: 0.8
      min_p: 0.05
      repeat_penalty: 1.1
      max_tokens: 512

# Creative writing task configurations
tasks:
  story_writing:
    description: "Long-form narrative writing"
    recommended_presets: ["balanced", "creative"]
    context_length: 2048
    
  dialogue:
    description: "Character dialogue and conversation"
    recommended_presets: ["focused", "balanced"]
    context_length: 1024
    
  brainstorming:
    description: "Idea generation and creative exploration"
    recommended_presets: ["creative", "natural"]
    context_length: 1024
    
  world_building:
    description: "Setting and world description"
    recommended_presets: ["balanced", "creative"]
    context_length: 2048

# Quality guidelines for creative writing
guidelines:
  coherence: "Maintain logical flow and consistency"
  creativity: "Balance originality with readability"
  engagement: "Keep the reader interested and invested"
  style: "Maintain consistent voice and tone"

# Sampling Strategy Configuration
# Defines different sampling methods and their parameter ranges

samplers:
  # Top-p (Nucleus) sampling
  top_p:
    name: "Top-p (Nucleus)"
    description: "Cumulative probability sampling"
    parameters:
      temperature: [0.7, 0.8, 0.9, 1.0]
      top_p: [0.85, 0.9, 0.95, 0.99]
      top_k: -1  # disabled
      min_p: 0.0
      repeat_penalty: 1.1
    
  # Top-k sampling
  top_k:
    name: "Top-k"
    description: "Top-k token sampling"
    parameters:
      temperature: [0.7, 0.8, 0.9, 1.0]
      top_k: [10, 20, 40, 80]
      top_p: 1.0  # disabled
      min_p: 0.0
      repeat_penalty: 1.1
      
  # Min-p sampling
  min_p:
    name: "Min-p"
    description: "Minimum probability threshold sampling"
    parameters:
      temperature: [0.7, 0.8, 0.9, 1.0]
      min_p: [0.01, 0.02, 0.05, 0.1]
      top_p: 1.0  # disabled
      top_k: -1   # disabled
      repeat_penalty: 1.1
      
  # Top-n-sigma sampling (novel method)
  top_n_sigma:
    name: "Top-n-sigma"
    description: "Standard deviation based sampling"
    parameters:
      temperature: [0.7, 0.8, 0.9, 1.0]
      n_sigma: [1.0, 1.5, 2.0, 2.5]
      top_p: 1.0  # disabled
      top_k: -1   # disabled
      min_p: 0.0
      repeat_penalty: 1.1
      
  # Temperature-only sampling
  temperature:
    name: "Temperature"
    description: "Pure temperature scaling"
    parameters:
      temperature: [0.1, 0.3, 0.5, 0.7, 0.9, 1.1, 1.3, 1.5]
      top_p: 1.0   # disabled
      top_k: -1    # disabled
      min_p: 0.0
      repeat_penalty: 1.0

# Sampling method implementations
implementations:
  standard:
    - "top_p"
    - "top_k" 
    - "temperature"
    - "min_p"
    
  experimental:
    - "top_n_sigma"
    
  research:
    # Future implementations
    - "contrastive_search"
    - "typical_sampling"
    - "eta_sampling" 