# Creative Writing Sampling Presets - Rigorous Testing Framework
# Systematically evaluating different sampling strategies for creative writing

# Core sampling presets for creative writing research
presets:
  # Model-specific defaults (dynamically selected based on model)
  model_default:
    description: "Dynamic model provider recommended settings"
    sampler: "model_specific"  # Special flag for dynamic selection
    
  # Model provider defaults
  llama_default:
    description: "Default Llama 3.1 provider-recommended settings"
    sampler: "top_p"
    parameters:
      temperature: 0.6
      top_p: 0.9
      max_tokens: 1024
      
  mistral_default:
    description: "Default Mistral/Ministral provider-recommended settings"
    sampler: "top_p"
    parameters:
      temperature: 0.3
      top_p: 1.0
      max_tokens: 1024
      
  mistral_small_default:
    description: "Mistral Small default settings with temp 0.15"
    sampler: "top_p"
    parameters:
      temperature: 0.15
      top_p: 1.0
      max_tokens: 1024
      
  qwen_default:
    description: "Default Qwen provider-recommended settings"
    sampler: "top_p"
    parameters:
      temperature: 0.7
      top_p: 0.8
      max_tokens: 1024

  # Min-p sampling configurations
  standard_minp:
    description: "Standard creative writing with min_p sampling"
    sampler: "min_p"
    parameters:
      temperature: 0.7
      min_p: 0.02
      max_tokens: 1024
      
  creative_minp:
    description: "Creative plus writing with min_p sampling"
    sampler: "min_p"
    parameters:
      temperature: 1.0
      min_p: 0.02
      max_tokens: 1024
      
  ultra_minp:
    description: "Creative ultra writing with min_p sampling"
    sampler: "min_p"
    parameters:
      temperature: 1.5
      min_p: 0.02
      max_tokens: 1024
      
  # Top-n-sigma sampling configurations (standardized naming, aligned with paper settings)
  standard_sigma:
    description: "Standard sigma sampling (paper settings: temp 1.5, sigma 1.0)"
    sampler: "top_n_sigma"
    parameters:
      temperature: 1.5
      top_n_sigma: 1.0
      max_tokens: 1024
      
  creative_sigma:
    description: "Creative sigma sampling with moderate temperature"
    sampler: "top_n_sigma"
    parameters:
      temperature: 1.0
      top_n_sigma: 1.5
      max_tokens: 1024

# Model mapping for dynamic default selection
model_defaults:
  # Llama family models
  "llama": "llama_default"
  "llama-3": "llama_default"
  "llama-3.1": "llama_default"
  "llama-3.2": "llama_default"
  
  # Mistral family models
  "mistral": "mistral_default"
  "mistral-small": "mistral_small_default"
  "mistral-small-24b": "mistral_small_default"
  "mistral-nemo": "mistral_default"
  "mistral-nemo-12b": "mistral_default"
  "ministral": "mistral_default"
  "ministral-8b": "mistral_default"
  
  # Qwen family models
  "qwen": "qwen_default"
  "qwen2": "qwen_default"
  "qwen2.5": "qwen_default"
  "qwen-2.5-8b": "qwen_default"
  "qwen-2.5-14b": "qwen_default"
  
  # Fallback for unknown models
  "default": "llama_default"

# Creative writing task configurations for rigorous testing
tasks:
  short_story:
    description: "Short narrative fiction (500-1000 words)"
    test_presets: ["model_default", "standard_minp", "creative_minp", "ultra_minp"]
    context_length: 2048
    
  character_dialogue:
    description: "Character interaction and conversation"
    test_presets: ["model_default", "standard_minp", "creative_sigma"]
    context_length: 1024
    
  creative_exploration:
    description: "High-creativity narrative experiments"
    test_presets: ["creative_minp", "ultra_minp", "creative_sigma", "standard_sigma"]
    context_length: 2048
    
  experimental_writing:
    description: "Testing sigma sampling approaches"
    test_presets: ["standard_sigma", "creative_sigma"]
    context_length: 2048

# Test configuration for systematic evaluation
test_framework:
  primary_task: "short_story"
  evaluation_criteria:
    - "narrative_coherence"
    - "character_development" 
    - "creative_originality"
    - "stylistic_consistency"
    - "engagement_factor"
  
  sample_size_per_preset: 5
  test_prompts:
    - "Write a short story about discovering a hidden room in an old library"
    - "Create a story where the protagonist can hear other people's thoughts"
    - "Tell a tale about a world where colors have started disappearing"
    - "Write about someone who wakes up with a completely different personality"
    - "Create a story about a cafe that exists in multiple dimensions"

# Quality guidelines for creative writing
guidelines:
  coherence: "Maintain logical flow and consistency"
  creativity: "Balance originality with readability"
  engagement: "Keep the reader interested and invested"
  style: "Maintain consistent voice and tone"

# Sampling Strategy Configuration
# Defines different sampling methods and their parameter ranges

samplers:
  # Top-p (Nucleus) sampling
  top_p:
    name: "Top-p (Nucleus)"
    description: "Cumulative probability sampling"
    parameters:
      temperature: [0.7, 0.8, 0.9, 1.0]
      top_p: [0.85, 0.9, 0.95, 0.99]
      top_k: -1  # disabled
      min_p: 0.0
    
  # Top-k sampling
  top_k:
    name: "Top-k"
    description: "Top-k token sampling"
    parameters:
      temperature: [0.7, 0.8, 0.9, 1.0]
      top_k: [10, 20, 40, 80]
      top_p: 1.0  # disabled
      min_p: 0.0
      
  # Min-p sampling
  min_p:
    name: "Min-p"
    description: "Minimum probability threshold sampling"
    parameters:
      temperature: [0.7, 0.8, 0.9, 1.0]
      min_p: [0.01, 0.02, 0.05, 0.1]
      top_p: 1.0  # disabled
      top_k: -1   # disabled
      
  # Top-n-sigma sampling (novel method)
  top_n_sigma:
    name: "Top-n-sigma"
    description: "Standard deviation based sampling"
    parameters:
      temperature: [0.7, 1.0, 1.5, 2.0]
      top_n_sigma: [1.0, 1.5, 2.0, 2.5]  # Updated parameter name for consistency
      top_p: 1.0  # disabled
      top_k: -1   # disabled
      min_p: 0.0
      
  # Temperature-only sampling
  temperature:
    name: "Temperature"
    description: "Pure temperature scaling"
    parameters:
      temperature: [0.1, 0.3, 0.5, 0.7, 0.9, 1.1, 1.3, 1.5]
      top_p: 1.0   # disabled
      top_k: -1    # disabled
      min_p: 0.0

# Sampling method implementations
implementations:
  standard:
    - "top_p"
    - "top_k" 
    - "temperature"
    - "min_p"
    
  experimental:
    - "top_n_sigma"
    
  research:
    # Future implementations
    - "contrastive_search"
    - "typical_sampling"
    - "eta_sampling" 